# ProBot Request Info (https://probot.github.io/apps/request-info/)

# Required Comment to reply with
requestInfoReplyComment: >
  Please provide some more information with this issue/ merge request! Thanks 😊

# OPTIONAL default titles to check against for lack of descriptiveness
# MUST BE ALL LOWERCASE
requestInfoDefaultTitles:
  - update readme.md
  - updates

# OPTIONAL Label to be added to Issues and Pull Requests with insufficient information given
requestInfoLabelToAdd: 'need more info'
